using System;
using System.Collections.Generic;

namespace Elin_ItemRelocator {
    public static class RelocatorLang {
        public enum LangKey {
            Settings, Execute, Relocate,
            Rarity, Category, Text, Enchant, Remove, Edit,
            Enable, Disable, Title, Operator, Preview, Scope,
            SelectEnchant, Msg_ContainerFull, Msg_RelocatedResult, Msg_NoMatchLog,
            GenLvl, Dna, DnaContent, Not, Weight,
            PresetName, Msg_Saved, Msg_Loaded,
            Presets, Rename, Delete, Msg_Renamed, Msg_Deleted, Msg_RenamePrompt, Msg_FileExists,
            Parent, Move, Msg_Moved,
            AddRule, NewRuleName,
            Material, Bless, Stolen, StateNormal, StateBlessed, StateCursed, StateDoomed,
            StolenState, IdentifiedState,
            ScopeBoth, Inventory, Zone,
            Enhancement, EditEnhancement,
            Identified, StateIdentified, StateUnidentified,
            ResetRules, ResetRulesConfirm, Msg_RulesCleared, Details,
            SortLabel, SortDefault, SortAsc, SortDesc,
            SortPriceAsc, SortPriceDesc, SortMagAsc, SortMagDesc,
            SortTotalEnchantMagDesc, SortWeightAsc, SortWeightDesc,
            SortUnitWeightAsc, SortUnitWeightDesc, SortUidAsc, SortUidDesc,
            Overwrite, Msg_MigrateConfirm, Msg_MigrateFailed, EnchantOr
        }

        private static Dictionary<LangKey, string[]> _dict = new() {
            [LangKey.Settings] = ["Settings", "設定"],
            [LangKey.Relocate] = ["Relocate", "アイテム転送"],
            [LangKey.Execute] = ["Relocate All", "全て転送"],
            [LangKey.Rarity] = ["Rarity", "レアリティ"],
            [LangKey.Category] = ["Category", "カテゴリ"],
            [LangKey.Text] = ["Item Name", "アイテム名"],
            [LangKey.Enchant] = ["Enchant", "エンチャント"],
            [LangKey.Remove] = ["Remove", "削除"],
            [LangKey.Edit] = ["Edit", "編集"],
            [LangKey.Enable] = ["Enable", "有効"],
            [LangKey.Disable] = ["Disable", "無効"],
            [LangKey.Title] = ["Item Relocator", "アイテムリロケータ"],
            [LangKey.Operator] = ["Operator", "演算子"],
            [LangKey.Preview] = ["Preview", "プレビュー"],
            [LangKey.Scope] = ["Scope", "範囲"],
            [LangKey.Inventory] = ["Inventory", "持ち物"],
            [LangKey.Zone] = ["Zone", "地面"],
            [LangKey.ScopeBoth] = ["Inventory+Zone", "持ち物+地面"],
            [LangKey.SelectEnchant] = ["Select Enchant", "エンチャント選択"],
            [LangKey.Msg_ContainerFull] = ["Container is full.", "コンテナが一杯です。"],
            [LangKey.Msg_RelocatedResult] = ["Relocated {0} stacks to {1}.", "{0}個のスタックを{1}に移動した。"],
            [LangKey.Msg_NoMatchLog] = ["No matching items found.", "条件に合うアイテムが見つからない。"],
            [LangKey.SortLabel] = ["Sort: ", "並び替え: "],
            [LangKey.SortDefault] = ["Default", "検索ヒット順(Default)"],
            [LangKey.SortPriceAsc] = ["Price (Low to High)", "価格 (安い順)"],
            [LangKey.SortPriceDesc] = ["Price (High to Low)", "価格 (高い順)"],
            [LangKey.SortMagAsc] = ["Enchant (Weak to Strong)", "エンチャント強度 (弱い順)"],
            [LangKey.SortMagDesc] = ["Enchant (Strong to Weak)", "エンチャント強度 (強い順)"],
            [LangKey.SortTotalEnchantMagDesc] = ["Sort: ALL Enchant (High to Low)", "総エンチャント強度 (降順)"],
            [LangKey.GenLvl] = ["Gen Lvl", "生成Lv"],
            [LangKey.Dna] = ["DNA Strength", "DNA消費FP"],
            [LangKey.DnaContent] = ["DNA Content", "DNA補正内容"],
            [LangKey.Not] = ["N", "否"],
            [LangKey.Weight] = ["Weight", "重量"],
            [LangKey.SortWeightAsc] = ["Total Weight (Lighest)", "総重量 (軽い順)"],
            [LangKey.SortWeightDesc] = ["Total Weight (Heaviest)", "総重量 (重い順)"],
            [LangKey.SortUnitWeightAsc] = ["Unit Weight (Lighest)", "単体重量 (軽い順)"],
            [LangKey.SortUnitWeightDesc] = ["Unit Weight (Heaviest)", "単体重量 (重い順)"],
            [LangKey.SortUidAsc] = ["UID Asc (Oldest)", "生成順 (古い順)"],
            [LangKey.SortUidDesc] = ["UID Desc (Newest)", "生成順 (新しい順)"],
            [LangKey.PresetName] = ["Preset Name", "プリセット名"],
            [LangKey.Msg_Saved] = ["Preset saved: {0}", "プリセットを保存しました: {0}"],
            [LangKey.Msg_Loaded] = ["Preset loaded.", "プリセットを読み込みました。"],
            [LangKey.Presets] = ["Presets", "プリセット"],
            [LangKey.Rename] = ["Rename", "名前変更"],
            [LangKey.Delete] = ["Delete", "削除"],
            [LangKey.Msg_Renamed] = ["Renamed preset to {0}.", "プリセット名を {0} に変更しました。"],
            [LangKey.Msg_Deleted] = ["Deleted preset: {0}", "プリセット {0} を削除しました。"],
            [LangKey.Msg_FileExists] = ["Preset already exists.", "同名のプリセットが既に存在します。"],
            [LangKey.Msg_RenamePrompt] = ["Enter new name", "新しい名前を入力"],
            [LangKey.Parent] = ["Location", "場所"],
            [LangKey.Move] = ["Move", "転送"],
            [LangKey.Msg_Moved] = ["Moved {0}.", "{0}を転送しました。"],
            [LangKey.AddRule] = ["Add Rule", "ルール追加"],
            [LangKey.NewRuleName] = ["Rule", "ルール"],
            [LangKey.Material] = ["Material", "素材"],
            [LangKey.Bless] = ["State (Bless)", "祝福状態"],
            [LangKey.StolenState] = ["State (Stolen)", "盗品状態"],
            [LangKey.Stolen] = ["Stolen", "盗品"],
            [LangKey.StateNormal] = ["Normal", "通常"],
            [LangKey.StateBlessed] = ["Blessed", "祝福"],
            [LangKey.StateCursed] = ["Cursed", "呪い"],
            [LangKey.StateDoomed] = ["Doomed", "堕落"],
            [LangKey.Enhancement] = ["Enhancement", "品質"],
            [LangKey.EditEnhancement] = ["Edit Enhancement (e.g. >=2)", "品質設定 (例: >=2)"],
            [LangKey.IdentifiedState] = ["State (Identified)", "鑑定状態"],
            [LangKey.Identified] = ["Identified", "鑑定済み"],
            [LangKey.StateIdentified] = ["Yes (Identified)", "鑑定済み"],
            [LangKey.StateUnidentified] = ["No (Unidentified)", "未鑑定"],
            [LangKey.ResetRules] = ["Reset Conditions", "条件初期化"],
            [LangKey.ResetRulesConfirm] = ["Reset all filter conditions (clear text cache etc)?", "編集中の条件をすべて消去しますか？"],
            [LangKey.Msg_RulesCleared] = ["Conditions cleared.", "条件を消去しました。"],
            [LangKey.Details] = ["Details", "詳細"],
            [LangKey.SortAsc] = ["Asc", "昇順"],
            [LangKey.SortDesc] = ["Desc", "降順"],
            [LangKey.Overwrite] = ["Overwrite", "上書き保存"],
            [LangKey.Msg_MigrateConfirm] = ["Old preset format detected. Update format?", "古い形式のプリセットを検出しました。形式を更新して上書きしますか？"],
            [LangKey.Msg_MigrateFailed] = ["Migration failed at step v{0}->v{1}: {2}", "v{0}からv{1}への移行に失敗しました: {2}"],
            [LangKey.EnchantOr] = ["Enchant", "エンチャント"]
        };

        public static string GetText(LangKey key) =>
            _dict.TryGetValue(key, out var val) ? val[Lang.langCode == "JP" ? 1 : 0] : key.ToString();
    }
}
