"""
C# Code Generator for Arena Flags

Generates strongly-typed C# classes from flag_definitions.py.
Output: src/Generated/ArenaFlags.cs
"""
import os
import sys
from datetime import datetime

# Path setup
BUILDER_DIR = os.path.dirname(os.path.abspath(__file__))
TOOLS_DIR = os.path.dirname(BUILDER_DIR)
COMMON_DIR = os.path.join(TOOLS_DIR, 'common')
sys.path.append(TOOLS_DIR)
sys.path.append(COMMON_DIR)

from flag_definitions import (
    get_all_flags, get_all_enums,
    EnumFlag, IntFlag, BoolFlag, StringFlag,
    PREFIX
)


def to_pascal_case(snake_str: str) -> str:
    """Convert snake_case or dot.case to PascalCase"""
    components = snake_str.replace('.', '_').split('_')
    return ''.join(x.title() for x in components)


def generate_csharp() -> str:
    """Generate C# source code"""
    lines = []

    lines.append("// <auto-generated>")
    lines.append(f"// Generated by generate_flags.py at {datetime.now().isoformat()}")
    lines.append("// Do not edit manually. Edit tools/flag_definitions.py instead.")
    lines.append("// </auto-generated>")
    lines.append("")
    lines.append("namespace Elin_SukutsuArena.Flags")
    lines.append("{")

    # Generate Enums
    lines.append("    #region Enums")
    lines.append("")
    for enum_type in get_all_enums():
        lines.append(f"    /// <summary>{enum_type.__doc__ or enum_type.__name__}</summary>")
        lines.append(f"    public enum {enum_type.__name__}")
        lines.append("    {")
        for member in enum_type:
            pascal_name = to_pascal_case(member.name)
            lines.append(f'        {pascal_name},  // "{member.value}"')
        lines.append("    }")
        lines.append("")
    lines.append("    #endregion")
    lines.append("")

    # Generate Flag Keys
    lines.append("    /// <summary>")
    lines.append(f"    /// フラグキー定数クラス (Prefix: {PREFIX})")
    lines.append("    /// </summary>")
    lines.append("    public static class ArenaFlagKeys")
    lines.append("    {")
    lines.append(f'        public const string Prefix = "{PREFIX}";')
    lines.append("")

    lines.append("        #region Player Flags")
    for flag in get_all_flags():
        if flag.key.startswith("player."):
            short_key = flag.key.replace("player.", "")
            const_name = to_pascal_case(short_key)
            lines.append(f'        /// <summary>{flag.description}</summary>')
            lines.append(f'        public const string {const_name} = "{flag.full_key}";')
    lines.append("        #endregion")
    lines.append("")

    lines.append("        #region Relationship Flags")
    for flag in get_all_flags():
        if flag.key.startswith("rel."):
            short_key = flag.key.replace("rel.", "Rel")
            const_name = to_pascal_case(short_key)
            lines.append(f'        /// <summary>{flag.description}</summary>')
            lines.append(f'        public const string {const_name} = "{flag.full_key}";')
    lines.append("        #endregion")

    lines.append("    }")
    lines.append("")

    # Generate Helper Methods for Enum conversion
    lines.append("    /// <summary>")
    lines.append("    /// Enum値とフラグ文字列の変換ヘルパー")
    lines.append("    /// </summary>")
    lines.append("    public static class ArenaFlagHelpers")
    lines.append("    {")

    for enum_type in get_all_enums():
        lines.append(f"        public static string ToFlagValue({enum_type.__name__} value)")
        lines.append("        {")
        lines.append("            return value switch")
        lines.append("            {")
        for member in enum_type:
            pascal_name = to_pascal_case(member.name)
            lines.append(f'                {enum_type.__name__}.{pascal_name} => "{member.value}",')
        lines.append('                _ => ""')
        lines.append("            };")
        lines.append("        }")
        lines.append("")

        lines.append(f"        public static {enum_type.__name__}? Parse{enum_type.__name__}(string value)")
        lines.append("        {")
        lines.append("            return value switch")
        lines.append("            {")
        for member in enum_type:
            pascal_name = to_pascal_case(member.name)
            lines.append(f'                "{member.value}" => {enum_type.__name__}.{pascal_name},')
        lines.append("                _ => null")
        lines.append("            };")
        lines.append("        }")
        lines.append("")

    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


def main():
    # Determine output path
    # script_dir = BUILDER_DIR
    project_root = os.path.dirname(TOOLS_DIR)
    output_dir = os.path.join(project_root, "src", "Generated")
    output_file = os.path.join(output_dir, "ArenaFlags.cs")

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Generate and write
    csharp_code = generate_csharp()
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(csharp_code)

    print(f"Generated: {output_file}")
    print(f"  - {len(get_all_enums())} enums")
    print(f"  - {len(get_all_flags())} flag keys")


if __name__ == "__main__":
    main()
