"""
C# Code Generator for Arena Quest Definitions

Generates strongly-typed C# classes from quest_dependencies.py.
Output: src/Generated/ArenaQuestData.cs
"""
import os
import sys
from datetime import datetime

# Path setup
BUILDER_DIR = os.path.dirname(os.path.abspath(__file__))
TOOLS_DIR = os.path.dirname(BUILDER_DIR)
COMMON_DIR = os.path.join(TOOLS_DIR, 'common')
sys.path.append(TOOLS_DIR)
sys.path.append(COMMON_DIR)

from flag_definitions import Phase, Actors, PREFIX
from quest_dependencies import QUEST_DEFINITIONS, QuestType


def to_pascal_case(snake_str: str) -> str:
    """Convert snake_case or dot.case to PascalCase"""
    components = snake_str.replace('.', '_').replace('-', '_').split('_')
    return ''.join(x.title() for x in components)


def escape_csharp_string(s: str) -> str:
    """Escape special characters for C# string literal"""
    if s is None:
        return "null"
    return s.replace('\\', '\\\\').replace('"', '\\"')


def generate_csharp() -> str:
    """Generate C# source code for quest data"""
    lines = []

    lines.append("// <auto-generated>")
    lines.append(f"// Generated by generate_quest_data.py at {datetime.now().isoformat()}")
    lines.append("// Do not edit manually. Edit tools/common/quest_dependencies.py instead.")
    lines.append("// </auto-generated>")
    lines.append("")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append("namespace Elin_SukutsuArena.Quests")
    lines.append("{")

    # Generate StoryPhase enum
    lines.append("    /// <summary>")
    lines.append("    /// ストーリーフェーズ（クエスト依存関係管理用）")
    lines.append("    /// </summary>")
    lines.append("    public enum StoryPhase")
    lines.append("    {")
    for i, phase in enumerate(Phase):
        lines.append(f'        {to_pascal_case(phase.name)} = {i},  // {phase.value}')
    lines.append("    }")
    lines.append("")

    # Generate QuestType enum
    lines.append("    /// <summary>")
    lines.append("    /// クエストの種類")
    lines.append("    /// </summary>")
    lines.append("    public enum ArenaQuestType")
    lines.append("    {")
    for qt in QuestType:
        lines.append(f'        {to_pascal_case(qt.name)},  // {qt.value}')
    lines.append("    }")
    lines.append("")

    # Generate NpcId constants
    lines.append("    /// <summary>")
    lines.append("    /// NPC ID定数")
    lines.append("    /// </summary>")
    lines.append("    public static class ArenaNpcIds")
    lines.append("    {")
    lines.append(f'        public const string Lily = "{Actors.LILY}";')
    lines.append(f'        public const string Balgas = "{Actors.BALGAS}";')
    lines.append(f'        public const string Zek = "{Actors.ZEK}";')
    lines.append(f'        public const string Astaroth = "{Actors.ASTAROTH}";')
    lines.append("    }")
    lines.append("")

    # Generate QuestDefinition class
    lines.append("    /// <summary>")
    lines.append("    /// クエスト定義")
    lines.append("    /// </summary>")
    lines.append("    public class ArenaQuestDefinition")
    lines.append("    {")
    lines.append("        public string QuestId { get; set; }")
    lines.append("        public ArenaQuestType QuestType { get; set; }")
    lines.append("        public string DramaId { get; set; }")
    lines.append("        public string DisplayNameJP { get; set; }")
    lines.append("        public string DisplayNameEN { get; set; }")
    lines.append("        public string Description { get; set; }")
    lines.append("")
    lines.append("        // Phase system")
    lines.append("        public StoryPhase Phase { get; set; }")
    lines.append("        public string QuestGiver { get; set; }  // NPC ID or null for auto-trigger")
    lines.append("        public bool AutoTrigger { get; set; }")
    lines.append("        public StoryPhase? AdvancesPhase { get; set; }")
    lines.append("")
    lines.append("        // Requirements")
    lines.append("        public List<string> RequiredQuests { get; set; } = new List<string>();")
    lines.append("        public int Priority { get; set; }")
    lines.append("")
    lines.append("        public bool IsAutoTrigger => AutoTrigger && QuestGiver == null;")
    lines.append("        public bool IsNpcQuest => !string.IsNullOrEmpty(QuestGiver);")
    lines.append("    }")
    lines.append("")

    # Generate QuestDatabase
    lines.append("    /// <summary>")
    lines.append("    /// クエストデータベース")
    lines.append("    /// </summary>")
    lines.append("    public static class ArenaQuestDatabase")
    lines.append("    {")
    lines.append("        private static Dictionary<string, ArenaQuestDefinition> _quests;")
    lines.append("        private static Dictionary<string, List<ArenaQuestDefinition>> _npcQuests;")
    lines.append("        private static List<ArenaQuestDefinition> _autoTriggerQuests;")
    lines.append("")
    lines.append("        public static IReadOnlyDictionary<string, ArenaQuestDefinition> AllQuests")
    lines.append("        {")
    lines.append("            get { EnsureInitialized(); return _quests; }")
    lines.append("        }")
    lines.append("")
    lines.append("        public static IReadOnlyDictionary<string, List<ArenaQuestDefinition>> NpcQuests")
    lines.append("        {")
    lines.append("            get { EnsureInitialized(); return _npcQuests; }")
    lines.append("        }")
    lines.append("")
    lines.append("        public static IReadOnlyList<ArenaQuestDefinition> AutoTriggerQuests")
    lines.append("        {")
    lines.append("            get { EnsureInitialized(); return _autoTriggerQuests; }")
    lines.append("        }")
    lines.append("")
    lines.append("        public static ArenaQuestDefinition GetQuest(string questId)")
    lines.append("        {")
    lines.append("            EnsureInitialized();")
    lines.append("            return _quests.TryGetValue(questId, out var quest) ? quest : null;")
    lines.append("        }")
    lines.append("")
    lines.append("        public static List<ArenaQuestDefinition> GetQuestsForNpc(string npcId)")
    lines.append("        {")
    lines.append("            EnsureInitialized();")
    lines.append("            return _npcQuests.TryGetValue(npcId, out var quests) ? quests : new List<ArenaQuestDefinition>();")
    lines.append("        }")
    lines.append("")
    lines.append("        private static void EnsureInitialized()")
    lines.append("        {")
    lines.append("            if (_quests != null) return;")
    lines.append("            Initialize();")
    lines.append("        }")
    lines.append("")
    lines.append("        private static void Initialize()")
    lines.append("        {")
    lines.append("            _quests = new Dictionary<string, ArenaQuestDefinition>();")
    lines.append("            _npcQuests = new Dictionary<string, List<ArenaQuestDefinition>>();")
    lines.append("            _autoTriggerQuests = new List<ArenaQuestDefinition>();")
    lines.append("")

    # Generate quest data
    for quest in QUEST_DEFINITIONS:
        quest_type_pascal = to_pascal_case(quest.quest_type.name)
        phase_pascal = to_pascal_case(quest.phase.name) if quest.phase else "Prologue"
        advances_phase = f"StoryPhase.{to_pascal_case(quest.advances_phase.name)}" if quest.advances_phase else "null"
        quest_giver = f'"{quest.quest_giver}"' if quest.quest_giver else "null"

        lines.append(f'            var q_{quest.quest_id.replace("-", "_")} = new ArenaQuestDefinition')
        lines.append("            {")
        lines.append(f'                QuestId = "{quest.quest_id}",')
        lines.append(f'                QuestType = ArenaQuestType.{quest_type_pascal},')
        lines.append(f'                DramaId = "{quest.drama_id}",')
        lines.append(f'                DisplayNameJP = "{escape_csharp_string(quest.display_name_jp)}",')
        lines.append(f'                DisplayNameEN = "{escape_csharp_string(quest.display_name_en)}",')
        lines.append(f'                Description = "{escape_csharp_string(quest.description)}",')
        lines.append(f'                Phase = StoryPhase.{phase_pascal},')
        lines.append(f'                QuestGiver = {quest_giver},')
        lines.append(f'                AutoTrigger = {str(quest.auto_trigger).lower()},')
        lines.append(f'                AdvancesPhase = {advances_phase},')
        if quest.required_quests:
            req_list = ', '.join([f'"{q}"' for q in quest.required_quests])
            lines.append(f'                RequiredQuests = new List<string> {{ {req_list} }},')
        lines.append(f'                Priority = {quest.priority}')
        lines.append("            };")
        lines.append(f'            _quests["{quest.quest_id}"] = q_{quest.quest_id.replace("-", "_")};')

        if quest.auto_trigger:
            lines.append(f'            _autoTriggerQuests.Add(q_{quest.quest_id.replace("-", "_")});')

        if quest.quest_giver:
            lines.append(f'            if (!_npcQuests.ContainsKey("{quest.quest_giver}"))')
            lines.append(f'                _npcQuests["{quest.quest_giver}"] = new List<ArenaQuestDefinition>();')
            lines.append(f'            _npcQuests["{quest.quest_giver}"].Add(q_{quest.quest_id.replace("-", "_")});')

        lines.append("")

    lines.append("            // Sort auto-trigger quests by priority")
    lines.append("            _autoTriggerQuests.Sort((a, b) => b.Priority.CompareTo(a.Priority));")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)


def main():
    # Determine output path
    project_root = os.path.dirname(TOOLS_DIR)
    output_dir = os.path.join(project_root, "src", "Generated")
    output_file = os.path.join(output_dir, "ArenaQuestData.cs")

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Generate and write
    csharp_code = generate_csharp()
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(csharp_code)

    # Count statistics
    auto_trigger_count = sum(1 for q in QUEST_DEFINITIONS if q.auto_trigger)
    npc_quest_count = sum(1 for q in QUEST_DEFINITIONS if q.quest_giver)

    print(f"Generated: {output_file}")
    print(f"  - {len(QUEST_DEFINITIONS)} quest definitions")
    print(f"  - {len(Phase)} story phases")
    print(f"  - {auto_trigger_count} auto-trigger quests")
    print(f"  - {npc_quest_count} NPC-initiated quests")


if __name__ == "__main__":
    main()
